export default {
  data: () => ({
    cities: [
      'BANGUED (Capital)',
      'BOLINEY',
      'BUCAY',
      'BUCLOC',
      'DAGUIOMAN',
      'DANGLAS',
      'DOLORES',
      'LA PAZ',
      'LACUB',
      'LAGANGILANG',
      'LAGAYAN',
      'LANGIDEN',
      'LICUAN-BAAY (LICUAN)',
      'LUBA',
      'MALIBCONG',
      'MANABO',
      'PEÑARRUBIA',
      'PIDIGAN',
      'PILAR',
      'SALLAPADAN',
      'SAN ISIDRO',
      'SAN JUAN',
      'SAN QUINTIN',
      'TAYUM',
      'TINEG',
      'TUBO',
      'VILLAVICIOSA',
      'BUENAVISTA',
      'CARMEN',
      'CITY OF BUTUAN (Capital)',
      'CITY OF CABADBARAN',
      'JABONGA',
      'KITCHARAO',
      'LAS NIEVES',
      'MAGALLANES',
      'NASIPIT',
      'REMEDIOS T. ROMUALDEZ',
      'SANTIAGO',
      'TUBAY',
      'BUNAWAN',
      'CITY OF BAYUGAN',
      'ESPERANZA',
      'LA PAZ',
      'LORETO',
      'PROSPERIDAD (Capital)',
      'ROSARIO',
      'SAN FRANCISCO',
      'SAN LUIS',
      'SANTA JOSEFA',
      'SIBAGAT',
      'TALACOGON',
      'TRENTO',
      'VERUELA',
      'ALTAVAS',
      'BALETE',
      'BANGA',
      'BATAN',
      'BURUANGA',
      'IBAJAY',
      'KALIBO (Capital)',
      'LEZO',
      'LIBACAO',
      'MADALAG',
      'MAKATO',
      'MALAY',
      'MALINAO',
      'NABAS',
      'NEW WASHINGTON',
      'NUMANCIA',
      'TANGALAN',
      'BACACAY',
      'CAMALIG',
      'CITY OF LEGAZPI (Capital)',
      'CITY OF LIGAO',
      'CITY OF TABACO',
      'DARAGA (LOCSIN)',
      'GUINOBATAN',
      'JOVELLAR',
      'LIBON',
      'MALILIPOT',
      'MALINAO',
      'MANITO',
      'OAS',
      'PIO DURAN',
      'POLANGUI',
      'RAPU-RAPU',
      'SANTO DOMINGO (LIBOG)',
      'TIWI',
      'ANINI-Y',
      'BARBAZA',
      'BUGASONG',
      'CALUYA',
      'CULASI',
      'HAMTIC',
      'LAUA-AN',
      'LIBERTAD',
      'PANDAN',
      'PATNONGON',
      'SAN JOSE (Capital)',
      'SAN REMIGIO',
      'SEBASTE',
      'SIBALOM',
      'TIBIAO',
      'TOBIAS FORNIER (DAO)',
      'VALDERRAMA',
      'CALANASAN (BAYAG)',
      'CONNER',
      'FLORA',
      'KABUGAO (Capital)',
      'LUNA',
      'PUDTOL',
      'SANTA MARCELA',
      'BALER (Capital)',
      'CASIGURAN',
      'DILASAG',
      'DINALUNGAN',
      'DINGALAN',
      'DIPACULAO',
      'MARIA AURORA',
      'SAN LUIS',
      'AKBAR',
      'AL-BARKA',
      'CITY OF LAMITAN (Capital)',
      'HADJI MOHAMMAD AJUL',
      'HADJI MUHTAMAD',
      'LANTAWAN',
      'MALUSO',
      'SUMISIP',
      'TABUAN-LASA',
      'TIPO-TIPO',
      'TUBURAN',
      'UNGKAYA PUKAN',
      'ABUCAY',
      'BAGAC',
      'CITY OF BALANGA (Capital)',
      'DINALUPIHAN',
      'HERMOSA',
      'LIMAY',
      'MARIVELES',
      'MORONG',
      'ORANI',
      'ORION',
      'PILAR',
      'SAMAL',
      'BASCO (Capital)',
      'ITBAYAT',
      'IVANA',
      'MAHATAO',
      'SABTANG',
      'UYUGAN',
      'AGONCILLO',
      'ALITAGTAG',
      'BALAYAN',
      'BALETE',
      'BATANGAS CITY (Capital)',
      'BAUAN',
      'CALACA',
      'CALATAGAN',
      'CITY OF LIPA',
      'CITY OF STO. TOMAS',
      'CITY OF TANAUAN',
      'CUENCA',
      'IBAAN',
      'LAUREL',
      'LEMERY',
      'LIAN',
      'LOBO',
      'MABINI',
      'MALVAR',
      'MATAASNAKAHOY',
      'NASUGBU',
      'PADRE GARCIA',
      'ROSARIO',
      'SAN JOSE',
      'SAN JUAN',
      'SAN LUIS',
      'SAN NICOLAS',
      'SAN PASCUAL',
      'SANTA TERESITA',
      'TAAL',
      'TALISAY',
      'TAYSAN',
      'TINGLOY',
      'TUY',
      'ATOK',
      'BAKUN',
      'BOKOD',
      'BUGUIAS',
      'CITY OF BAGUIO',
      'ITOGON',
      'KABAYAN',
      'KAPANGAN',
      'KIBUNGAN',
      'LA TRINIDAD (Capital)',
      'MANKAYAN',
      'SABLAN',
      'TUBA',
      'TUBLAY',
      'ALMERIA',
      'BILIRAN',
      'CABUCGAYAN',
      'CAIBIRAN',
      'CULABA',
      'KAWAYAN',
      'MARIPIPI',
      'NAVAL (Capital)',
      'ALBURQUERQUE',
      'ALICIA',
      'ANDA',
      'ANTEQUERA',
      'BACLAYON',
      'BALILIHAN',
      'BATUAN',
      'BIEN UNIDO',
      'BILAR',
      'BUENAVISTA',
      'CALAPE',
      'CANDIJAY',
      'CARMEN',
      'CATIGBIAN',
      'CITY OF TAGBILARAN (Capital)',
      'CLARIN',
      'CORELLA',
      'CORTES',
      'DAGOHOY',
      'DANAO',
      'DAUIS',
      'DIMIAO',
      'DUERO',
      'GARCIA HERNANDEZ',
      'GETAFE',
      'GUINDULMAN',
      'INABANGA',
      'JAGNA',
      'LILA',
      'LOAY',
      'LOBOC',
      'LOON',
      'MABINI',
      'MARIBOJOC',
      'PANGLAO',
      'PILAR',
      'PRES. CARLOS P. GARCIA (PITOGO)',
      'SAGBAYAN (BORJA)',
      'SAN ISIDRO',
      'SAN MIGUEL',
      'SEVILLA',
      'SIERRA BULLONES',
      'SIKATUNA',
      'TALIBON',
      'TRINIDAD',
      'TUBIGON',
      'UBAY',
      'VALENCIA',
      'BAUNGON',
      'CABANGLASAN',
      'CITY OF MALAYBALAY (Capital)',
      'CITY OF VALENCIA',
      'DAMULOG',
      'DANGCAGAN',
      'DON CARLOS',
      'IMPASUG-ONG',
      'KADINGILAN',
      'KIBAWE',
      'KITAOTAO',
      'LANTAPAN',
      'LIBONA',
      'MALITBOG',
      'MANOLO FORTICH',
      'MARAMAG',
      'PANGANTUCAN',
      'QUEZON',
      'SAN FERNANDO',
      'SUMILAO',
      'TALAKAG',
      'ANGAT',
      'BALAGTAS (BIGAA)',
      'BALIUAG',
      'BOCAUE',
      'BULACAN',
      'BUSTOS',
      'CALUMPIT',
      'CITY OF MALOLOS (Capital)',
      'CITY OF MEYCAUAYAN',
      'CITY OF SAN JOSE DEL MONTE',
      'DOÑA REMEDIOS TRINIDAD',
      'GUIGUINTO',
      'HAGONOY',
      'MARILAO',
      'NORZAGARAY',
      'OBANDO',
      'PANDI',
      'PAOMBONG',
      'PLARIDEL',
      'PULILAN',
      'SAN ILDEFONSO',
      'SAN MIGUEL',
      'SAN RAFAEL',
      'SANTA MARIA',
      'ABULUG',
      'ALCALA',
      'ALLACAPAN',
      'AMULUNG',
      'APARRI',
      'BAGGAO',
      'BALLESTEROS',
      'BUGUEY',
      'CALAYAN',
      'CAMALANIUGAN',
      'CLAVERIA',
      'ENRILE',
      'GATTARAN',
      'GONZAGA',
      'IGUIG',
      'LAL-LO',
      'LASAM',
      'PAMPLONA',
      'PEÑABLANCA',
      'PIAT',
      'RIZAL',
      'SANCHEZ-MIRA',
      'SANTA ANA',
      'SANTA PRAXEDES',
      'SANTA TERESITA',
      'SANTO NIÑO (FAIRE)',
      'SOLANA',
      'TUAO',
      'TUGUEGARAO CITY (Capital)',
      'BASUD',
      'CAPALONGA',
      'DAET (Capital)',
      'JOSE PANGANIBAN',
      'LABO',
      'MERCEDES',
      'PARACALE',
      'SAN LORENZO RUIZ (IMELDA)',
      'SAN VICENTE',
      'SANTA ELENA',
      'TALISAY',
      'VINZONS',
      'BAAO',
      'BALATAN',
      'BATO',
      'BOMBON',
      'BUHI',
      'BULA',
      'CABUSAO',
      'CALABANGA',
      'CAMALIGAN',
      'CANAMAN',
      'CARAMOAN',
      'CITY OF IRIGA',
      'CITY OF NAGA',
      'DEL GALLEGO',
      'GAINZA',
      'GARCHITORENA',
      'GOA',
      'LAGONOY',
      'LIBMANAN',
      'LUPI',
      'MAGARAO',
      'MILAOR',
      'MINALABAC',
      'NABUA',
      'OCAMPO',
      'PAMPLONA',
      'PASACAO',
      'PILI (Capital)',
      'PRESENTACION (PARUBCAN)',
      'RAGAY',
      'SAGÑAY',
      'SAN FERNANDO',
      'SAN JOSE',
      'SIPOCOT',
      'SIRUMA',
      'TIGAON',
      'TINAMBAC',
      'CATARMAN',
      'GUINSILIBAN',
      'MAHINOG',
      'MAMBAJAO (Capital)',
      'SAGAY',
      'CITY OF ROXAS (Capital)',
      'CUARTERO',
      'DAO',
      'DUMALAG',
      'DUMARAO',
      'IVISAN',
      'JAMINDAN',
      'MA-AYON',
      'MAMBUSAO',
      'PANAY',
      'PANITAN',
      'PILAR',
      'PONTEVEDRA',
      'PRESIDENT ROXAS',
      'SAPI-AN',
      'SIGMA',
      'TAPAZ',
      'BAGAMANOC',
      'BARAS',
      'BATO',
      'CARAMORAN',
      'GIGMOTO',
      'PANDAN',
      'PANGANIBAN (PAYO)',
      'SAN ANDRES (CALOLBON)',
      'SAN MIGUEL',
      'VIGA',
      'VIRAC (Capital)',
      'ALFONSO',
      'AMADEO',
      'CARMONA',
      'CITY OF BACOOR',
      'CITY OF CAVITE',
      'CITY OF DASMARIÑAS',
      'CITY OF GENERAL TRIAS',
      'CITY OF IMUS',
      'CITY OF TAGAYTAY',
      'CITY OF TRECE MARTIRES (Capital)',
      'GEN. MARIANO ALVAREZ',
      'GENERAL EMILIO AGUINALDO',
      'INDANG',
      'KAWIT',
      'MAGALLANES',
      'MARAGONDON',
      'MENDEZ (MENDEZ-NUÑEZ)',
      'NAIC',
      'NOVELETA',
      'ROSARIO',
      'SILANG',
      'TANZA',
      'TERNATE',
      'ALCANTARA',
      'ALCOY',
      'ALEGRIA',
      'ALOGUINSAN',
      'ARGAO',
      'ASTURIAS',
      'BADIAN',
      'BALAMBAN',
      'BANTAYAN',
      'BARILI',
      'BOLJOON',
      'BORBON',
      'CARMEN',
      'CATMON',
      'CITY OF BOGO',
      'CITY OF CARCAR',
      'CITY OF CEBU (Capital)',
      'CITY OF LAPU-LAPU (OPON)',
      'CITY OF MANDAUE',
      'CITY OF NAGA',
      'CITY OF TALISAY',
      'CITY OF TOLEDO',
      'COMPOSTELA',
      'CONSOLACION',
      'CORDOVA',
      'DAANBANTAYAN',
      'DALAGUETE',
      'DANAO CITY',
      'DUMANJUG',
      'GINATILAN',
      'LILOAN',
      'MADRIDEJOS',
      'MALABUYOC',
      'MEDELLIN',
      'MINGLANILLA',
      'MOALBOAL',
      'OSLOB',
      'PILAR',
      'PINAMUNGAJAN',
      'PORO',
      'RONDA',
      'SAMBOAN',
      'SAN FERNANDO',
      'SAN FRANCISCO',
      'SAN REMIGIO',
      'SANTA FE',
      'SANTANDER',
      'SIBONGA',
      'SOGOD',
      'TABOGON',
      'TABUELAN',
      'TUBURAN',
      'TUDELA',
      'ALAMADA',
      'ALEOSAN',
      'ANTIPAS',
      'ARAKAN',
      'BANISILAN',
      'CARMEN',
      'CITY OF KIDAPAWAN (Capital)',
      'KABACAN',
      'LIBUNGAN',
      'MLANG',
      'MAGPET',
      'MAKILALA',
      'MATALAM',
      'MIDSAYAP',
      'PIGKAWAYAN',
      'PIKIT',
      'PRESIDENT ROXAS',
      'TULUNAN',
      'COMPOSTELA',
      'LAAK (SAN VICENTE)',
      'MABINI (DOÑA ALICIA)',
      'MACO',
      'MARAGUSAN (SAN MARIANO)',
      'MAWAB',
      'MONKAYO',
      'MONTEVISTA',
      'NABUNTURAN (Capital)',
      'NEW BATAAN',
      'PANTUKAN',
      'ASUNCION (SAUG)',
      'BRAULIO E. DUJALI',
      'CARMEN',
      'CITY OF PANABO',
      'CITY OF TAGUM (Capital)',
      'ISLAND GARDEN CITY OF SAMAL',
      'KAPALONG',
      'NEW CORELLA',
      'SAN ISIDRO',
      'SANTO TOMAS',
      'TALAINGOD',
      'BANSALAN',
      'CITY OF DAVAO',
      'CITY OF DIGOS (Capital)',
      'HAGONOY',
      'KIBLAWAN',
      'MAGSAYSAY',
      'MALALAG',
      'MATANAO',
      'PADADA',
      'SANTA CRUZ',
      'SULOP',
      'DON MARCELINO',
      'JOSE ABAD SANTOS (TRINIDAD)',
      'MALITA (Capital)',
      'SANTA MARIA',
      'SARANGANI',
      'BAGANGA',
      'BANAYBANAY',
      'BOSTON',
      'CARAGA',
      'CATEEL',
      'CITY OF MATI (Capital)',
      'GOVERNOR GENEROSO',
      'LUPON',
      'MANAY',
      'SAN ISIDRO',
      'TARRAGONA',
      'BASILISA (RIZAL)',
      'CAGDIANAO',
      'DINAGAT',
      'LIBJO (ALBOR)',
      'LORETO',
      'SAN JOSE (Capital)',
      'TUBAJON',
      'ARTECHE',
      'BALANGIGA',
      'BALANGKAYAN',
      'CAN-AVID',
      'CITY OF BORONGAN (Capital)',
      'DOLORES',
      'GENERAL MACARTHUR',
      'GIPORLOS',
      'GUIUAN',
      'HERNANI',
      'JIPAPAD',
      'LAWAAN',
      'LLORENTE',
      'MASLOG',
      'MAYDOLONG',
      'MERCEDES',
      'ORAS',
      'QUINAPONDAN',
      'SALCEDO',
      'SAN JULIAN',
      'SAN POLICARPO',
      'SULAT',
      'TAFT',
      'BUENAVISTA',
      'JORDAN (Capital)',
      'NUEVA VALENCIA',
      'SAN LORENZO',
      'SIBUNAG',
      'AGUINALDO',
      'ALFONSO LISTA (POTIA)',
      'ASIPULO',
      'BANAUE',
      'HINGYON',
      'HUNGDUAN',
      'KIANGAN',
      'LAGAWE (Capital)',
      'LAMUT',
      'MAYOYAO',
      'TINOC',
      'ADAMS',
      'BACARRA',
      'BADOC',
      'BANGUI',
      'BANNA (ESPIRITU)',
      'BURGOS',
      'CARASI',
      'CITY OF BATAC',
      'CITY OF LAOAG (Capital)',
      'CURRIMAO',
      'DINGRAS',
      'DUMALNEG',
      'MARCOS',
      'NUEVA ERA',
      'PAGUDPUD',
      'PAOAY',
      'PASUQUIN',
      'PIDDIG',
      'PINILI',
      'SAN NICOLAS',
      'SARRAT',
      'SOLSONA',
      'VINTAR',
      'ALILEM',
      'BANAYOYO',
      'BANTAY',
      'CABUGAO',
      'CAOAYAN',
      'CERVANTES',
      'CITY OF CANDON',
      'CITY OF VIGAN (Capital)',
      'GALIMUYOD',
      'GREGORIO DEL PILAR (CONCEPCION)',
      'LIDLIDDA',
      'MAGSINGAL',
      'NAGBUKEL',
      'NARVACAN',
      'QUIRINO (ANGKAKI)',
      'SALCEDO (BAUGEN)',
      'SAN EMILIO',
      'SAN ESTEBAN',
      'SAN ILDEFONSO',
      'SAN JUAN (LAPOG)',
      'SAN VICENTE',
      'SANTA',
      'SANTA CATALINA',
      'SANTA CRUZ',
      'SANTA LUCIA',
      'SANTA MARIA',
      'SANTIAGO',
      'SANTO DOMINGO',
      'SIGAY',
      'SINAIT',
      'SUGPON',
      'SUYO',
      'TAGUDIN',
      'AJUY',
      'ALIMODIAN',
      'ANILAO',
      'BADIANGAN',
      'BALASAN',
      'BANATE',
      'BAROTAC NUEVO',
      'BAROTAC VIEJO',
      'BATAD',
      'BINGAWAN',
      'CABATUAN',
      'CALINOG',
      'CARLES',
      'CITY OF ILOILO (Capital)',
      'CITY OF PASSI',
      'CONCEPCION',
      'DINGLE',
      'DUEÑAS',
      'DUMANGAS',
      'ESTANCIA',
      'GUIMBAL',
      'IGBARAS',
      'JANIUAY',
      'LAMBUNAO',
      'LEGANES',
      'LEMERY',
      'LEON',
      'MAASIN',
      'MIAGAO',
      'MINA',
      'NEW LUCENA',
      'OTON',
      'PAVIA',
      'POTOTAN',
      'SAN DIONISIO',
      'SAN ENRIQUE',
      'SAN JOAQUIN',
      'SAN MIGUEL',
      'SAN RAFAEL',
      'SANTA BARBARA',
      'SARA',
      'TIGBAUAN',
      'TUBUNGAN',
      'ZARRAGA',
      'ALICIA',
      'ANGADANAN',
      'AURORA',
      'BENITO SOLIVEN',
      'BURGOS',
      'CABAGAN',
      'CABATUAN',
      'CITY OF CAUAYAN',
      'CITY OF ILAGAN (Capital)',
      'CITY OF SANTIAGO',
      'CORDON',
      'DELFIN ALBANO (MAGSAYSAY)',
      'DINAPIGUE',
      'DIVILACAN',
      'ECHAGUE',
      'GAMU',
      'JONES',
      'LUNA',
      'MACONACON',
      'MALLIG',
      'NAGUILIAN',
      'PALANAN',
      'QUEZON',
      'QUIRINO',
      'RAMON',
      'REINA MERCEDES',
      'ROXAS',
      'SAN AGUSTIN',
      'SAN GUILLERMO',
      'SAN ISIDRO',
      'SAN MANUEL',
      'SAN MARIANO',
      'SAN MATEO',
      'SAN PABLO',
      'SANTA MARIA',
      'SANTO TOMAS',
      'TUMAUINI',
      'BALBALAN',
      'CITY OF TABUK (Capital)',
      'LUBUAGAN',
      'PASIL',
      'PINUKPUK',
      'RIZAL (LIWAN)',
      'TANUDAN',
      'TINGLAYAN',
      'AGOO',
      'ARINGAY',
      'BACNOTAN',
      'BAGULIN',
      'BALAOAN',
      'BANGAR',
      'BAUANG',
      'BURGOS',
      'CABA',
      'CITY OF SAN FERNANDO (Capital)',
      'LUNA',
      'NAGUILIAN',
      'PUGO',
      'ROSARIO',
      'SAN GABRIEL',
      'SAN JUAN',
      'SANTO TOMAS',
      'SANTOL',
      'SUDIPEN',
      'TUBAO',
      'ALAMINOS',
      'BAY',
      'CALAUAN',
      'CAVINTI',
      'CITY OF BIÑAN',
      'CITY OF CABUYAO',
      'CITY OF CALAMBA',
      'CITY OF SAN PABLO',
      'CITY OF SAN PEDRO',
      'CITY OF SANTA ROSA',
      'FAMY',
      'KALAYAAN',
      'LILIW',
      'LOS BAÑOS',
      'LUISIANA',
      'LUMBAN',
      'MABITAC',
      'MAGDALENA',
      'MAJAYJAY',
      'NAGCARLAN',
      'PAETE',
      'PAGSANJAN',
      'PAKIL',
      'PANGIL',
      'PILA',
      'RIZAL',
      'SANTA CRUZ (Capital)',
      'SANTA MARIA',
      'SINILOAN',
      'VICTORIA',
      'BACOLOD',
      'BALOI',
      'BAROY',
      'CITY OF ILIGAN',
      'KAPATAGAN',
      'KAUSWAGAN',
      'KOLAMBUGAN',
      'LALA',
      'LINAMON',
      'MAGSAYSAY',
      'MAIGO',
      'MATUNGAO',
      'MUNAI',
      'NUNUNGAN',
      'PANTAO RAGAT',
      'PANTAR',
      'POONA PIAGAPO',
      'SALVADOR',
      'SAPAD',
      'SULTAN NAGA DIMAPORO (KAROMATAN)',
      'TAGOLOAN',
      'TANGCAL',
      'TUBOD (Capital)',
      'AMAI MANABILANG (BUMBARAN)',
      'BACOLOD-KALAWI (BACOLOD GRANDE)',
      'BALABAGAN',
      'BALINDONG (WATU)',
      'BAYANG',
      'BINIDAYAN',
      'BUADIPOSO-BUNTONG',
      'BUBONG',
      'BUTIG',
      'CALANOGAS',
      'CITY OF MARAWI (Capital)',
      'DITSAAN-RAMAIN',
      'GANASSI',
      'KAPAI',
      'KAPATAGAN',
      'LUMBA-BAYABAO (MAGUING)',
      'LUMBACA-UNAYAN',
      'LUMBATAN',
      'LUMBAYANAGUE',
      'MADALUM',
      'MADAMBA',
      'MAGUING',
      'MALABANG',
      'MARANTAO',
      'MAROGONG',
      'MASIU',
      'MULONDO',
      'PAGAYAWAN (TATARIKAN)',
      'PIAGAPO',
      'PICONG (SULTAN GUMANDER)',
      'POONA BAYABAO (GATA)',
      'PUALAS',
      'SAGUIARAN',
      'SULTAN DUMALONDONG',
      'TAGOLOAN II',
      'TAMPARAN',
      'TARAKA',
      'TUBARAN',
      'TUGAYA',
      'WAO',
      'ABUYOG',
      'ALANGALANG',
      'ALBUERA',
      'BABATNGON',
      'BARUGO',
      'BATO',
      'BURAUEN',
      'CALUBIAN',
      'CAPOOCAN',
      'CARIGARA',
      'CITY OF BAYBAY',
      'CITY OF TACLOBAN (Capital)',
      'DAGAMI',
      'DULAG',
      'HILONGOS',
      'HINDANG',
      'INOPACAN',
      'ISABEL',
      'JARO',
      'JAVIER (BUGHO)',
      'JULITA',
      'KANANGA',
      'LA PAZ',
      'LEYTE',
      'MACARTHUR',
      'MAHAPLAG',
      'MATAG-OB',
      'MATALOM',
      'MAYORGA',
      'MERIDA',
      'ORMOC CITY',
      'PALO',
      'PALOMPON',
      'PASTRANA',
      'SAN ISIDRO',
      'SAN MIGUEL',
      'SANTA FE',
      'TABANGO',
      'TABONTABON',
      'TANAUAN',
      'TOLOSA',
      'TUNGA',
      'VILLABA',
      'AMPATUAN',
      'BARIRA',
      'BULDON',
      'BULUAN',
      'DATU ABDULLAH SANGKI',
      'DATU ANGGAL MIDTIMBANG',
      'DATU BLAH T. SINSUAT',
      'DATU HOFFER AMPATUAN',
      'DATU ODIN SINSUAT (DINAIG)',
      'DATU PAGLAS',
      'DATU PIANG',
      'DATU SALIBO',
      'DATU SAUDI-AMPATUAN',
      'DATU UNSAY',
      'GEN. S.K. PENDATUN',
      'GUINDULUNGAN',
      'KABUNTALAN (TUMBAO)',
      'MAMASAPANO',
      'MANGUDADATU',
      'MATANOG',
      'NORTHERN KABUNTALAN',
      'PAGAGAWAN',
      'PAGALUNGAN',
      'PAGLAT',
      'PANDAG',
      'PARANG',
      'RAJAH BUAYAN',
      'SHARIFF AGUAK (MAGANOY) (Capital)',
      'SHARIFF SAYDONA MUSTAPHA',
      'SOUTH UPI',
      'SULTAN KUDARAT (NULING)',
      'SULTAN MASTURA',
      'SULTAN SA BARONGIS (LAMBAYONG)',
      'TALAYAN',
      'TALITAY',
      'UPI',
      'BOAC (Capital)',
      'BUENAVISTA',
      'GASAN',
      'MOGPOG',
      'SANTA CRUZ',
      'TORRIJOS',
      'AROROY',
      'BALENO',
      'BALUD',
      'BATUAN',
      'CATAINGAN',
      'CAWAYAN',
      'CITY OF MASBATE (Capital)',
      'CLAVERIA',
      'DIMASALANG',
      'ESPERANZA',
      'MANDAON',
      'MILAGROS',
      'MOBO',
      'MONREAL',
      'PALANAS',
      'PIO V. CORPUZ (LIMBUHAN)',
      'PLACER',
      'SAN FERNANDO',
      'SAN JACINTO',
      'SAN PASCUAL',
      'USON',
      'ALORAN',
      'BALIANGAO',
      'BONIFACIO',
      'CALAMBA',
      'CITY OF OROQUIETA (Capital)',
      'CITY OF OZAMIZ',
      'CITY OF TANGUB',
      'CLARIN',
      'CONCEPCION',
      'DON VICTORIANO CHIONGBIAN  (DON MARIANO MARCOS)',
      'JIMENEZ',
      'LOPEZ JAENA',
      'PANAON',
      'PLARIDEL',
      'SAPANG DALAGA',
      'SINACABAN',
      'TUDELA',
      'ALUBIJID',
      'BALINGASAG',
      'BALINGOAN',
      'BINUANGAN',
      'CITY OF CAGAYAN DE ORO (Capital)',
      'CITY OF EL SALVADOR',
      'CITY OF GINGOOG',
      'CLAVERIA',
      'GITAGUM',
      'INITAO',
      'JASAAN',
      'KINOGUITAN',
      'LAGONGLONG',
      'LAGUINDINGAN',
      'LIBERTAD',
      'LUGAIT',
      'MAGSAYSAY (LINUGOS)',
      'MANTICAO',
      'MEDINA',
      'NAAWAN',
      'OPOL',
      'SALAY',
      'SUGBONGCOGON',
      'TAGOLOAN',
      'TALISAYAN',
      'VILLANUEVA',
      'BARLIG',
      'BAUKO',
      'BESAO',
      'BONTOC (Capital)',
      'NATONIN',
      'PARACELIS',
      'SABANGAN',
      'SADANGA',
      'SAGADA',
      'TADIAN',
      'NCR, CITY OF MANILA, FIRST DISTRICT (Not a Province)',
      'CITY OF LAS PIÑAS',
      'CITY OF MAKATI',
      'CITY OF MUNTINLUPA',
      'CITY OF PARAÑAQUE',
      'CITY OF TAGUIG',
      'PASAY CITY',
      'PATEROS',
      'CITY OF MANDALUYONG',
      'CITY OF MARIKINA',
      'CITY OF PASIG',
      'CITY OF SAN JUAN',
      'QUEZON CITY',
      'CITY OF CALOOCAN',
      'CITY OF MALABON',
      'CITY OF NAVOTAS',
      'CITY OF VALENZUELA',
      'BINALBAGAN',
      'CALATRAVA',
      'CANDONI',
      'CAUAYAN',
      'CITY OF BACOLOD (Capital)',
      'CITY OF BAGO',
      'CITY OF CADIZ',
      'CITY OF ESCALANTE',
      'CITY OF HIMAMAYLAN',
      'CITY OF KABANKALAN',
      'CITY OF LA CARLOTA',
      'CITY OF SAGAY',
      'CITY OF SAN CARLOS',
      'CITY OF SILAY',
      'CITY OF SIPALAY',
      'CITY OF TALISAY',
      'CITY OF VICTORIAS',
      'ENRIQUE B. MAGALONA (SARAVIA)',
      'HINIGARAN',
      'HINOBA-AN (ASIA)',
      'ILOG',
      'ISABELA',
      'LA CASTELLANA',
      'MANAPLA',
      'MOISES PADILLA (MAGALLON)',
      'MURCIA',
      'PONTEVEDRA',
      'PULUPANDAN',
      'SALVADOR BENEDICTO',
      'SAN ENRIQUE',
      'TOBOSO',
      'VALLADOLID',
      'AMLAN (AYUQUITAN)',
      'AYUNGON',
      'BACONG',
      'BASAY',
      'BINDOY (PAYABON)',
      'CITY OF BAIS',
      'CITY OF BAYAWAN (TULONG)',
      'CITY OF CANLAON',
      'CITY OF DUMAGUETE (Capital)',
      'CITY OF GUIHULNGAN',
      'CITY OF TANJAY',
      'DAUIN',
      'JIMALALUD',
      'LA LIBERTAD',
      'MABINAY',
      'MANJUYOD',
      'PAMPLONA',
      'SAN JOSE',
      'SANTA CATALINA',
      'SIATON',
      'SIBULAN',
      'TAYASAN',
      'VALENCIA (LUZURRIAGA)',
      'VALLEHERMOSO',
      'ZAMBOANGUITA',
      'ALLEN',
      'BIRI',
      'BOBON',
      'CAPUL',
      'CATARMAN (Capital)',
      'CATUBIG',
      'GAMAY',
      'LAOANG',
      'LAPINIG',
      'LAS NAVAS',
      'LAVEZARES',
      'LOPE DE VEGA',
      'MAPANAS',
      'MONDRAGON',
      'PALAPAG',
      'PAMBUJAN',
      'ROSARIO',
      'SAN ANTONIO',
      'SAN ISIDRO',
      'SAN JOSE',
      'SAN ROQUE',
      'SAN VICENTE',
      'SILVINO LOBOS',
      'VICTORIA',
      'ALIAGA',
      'BONGABON',
      'CABIAO',
      'CARRANGLAN',
      'CITY OF CABANATUAN',
      'CITY OF GAPAN',
      'CITY OF PALAYAN (Capital)',
      'CUYAPO',
      'GABALDON (BITULOK & SABANI)',
      'GENERAL MAMERTO NATIVIDAD',
      'GENERAL TINIO (PAPAYA)',
      'GUIMBA',
      'JAEN',
      'LAUR',
      'LICAB',
      'LLANERA',
      'LUPAO',
      'NAMPICUAN',
      'PANTABANGAN',
      'PEÑARANDA',
      'QUEZON',
      'RIZAL',
      'SAN ANTONIO',
      'SAN ISIDRO',
      'SAN JOSE CITY',
      'SAN LEONARDO',
      'SANTA ROSA',
      'SANTO DOMINGO',
      'SCIENCE CITY OF MUÑOZ',
      'TALAVERA',
      'TALUGTUG',
      'ZARAGOZA',
      'ALFONSO CASTANEDA',
      'AMBAGUIO',
      'ARITAO',
      'BAGABAG',
      'BAMBANG',
      'BAYOMBONG (Capital)',
      'DIADI',
      'DUPAX DEL NORTE',
      'DUPAX DEL SUR',
      'KASIBU',
      'KAYAPA',
      'QUEZON',
      'SANTA FE',
      'SOLANO',
      'VILLAVERDE',
      'ABRA DE ILOG',
      'CALINTAAN',
      'LOOC',
      'LUBANG',
      'MAGSAYSAY',
      'MAMBURAO (Capital)',
      'PALUAN',
      'RIZAL',
      'SABLAYAN',
      'SAN JOSE',
      'SANTA CRUZ',
      'BACO',
      'BANSUD',
      'BONGABONG',
      'BULALACAO (SAN PEDRO)',
      'CITY OF CALAPAN (Capital)',
      'GLORIA',
      'MANSALAY',
      'NAUJAN',
      'PINAMALAYAN',
      'POLA',
      'PUERTO GALERA',
      'ROXAS',
      'SAN TEODORO',
      'SOCORRO',
      'VICTORIA',
      'ABORLAN',
      'AGUTAYA',
      'ARACELI',
      'BALABAC',
      'BATARAZA',
      'BROOKES POINT',
      'BUSUANGA',
      'CAGAYANCILLO',
      'CITY OF PUERTO PRINCESA (Capital)',
      'CORON',
      'CULION',
      'CUYO',
      'DUMARAN',
      'EL NIDO (BACUIT)',
      'KALAYAAN',
      'LINAPACAN',
      'MAGSAYSAY',
      'NARRA',
      'QUEZON',
      'RIZAL (MARCOS)',
      'ROXAS',
      'SAN VICENTE',
      'SOFRONIO ESPAÑOLA',
      'TAYTAY',
      'APALIT',
      'ARAYAT',
      'BACOLOR',
      'CANDABA',
      'CITY OF ANGELES',
      'CITY OF SAN FERNANDO (Capital)',
      'FLORIDABLANCA',
      'GUAGUA',
      'LUBAO',
      'MABALACAT CITY',
      'MACABEBE',
      'MAGALANG',
      'MASANTOL',
      'MEXICO',
      'MINALIN',
      'PORAC',
      'SAN LUIS',
      'SAN SIMON',
      'SANTA ANA',
      'SANTA RITA',
      'SANTO TOMAS',
      'SASMUAN (Sexmoan)',
      'AGNO',
      'AGUILAR',
      'ALCALA',
      'ANDA',
      'ASINGAN',
      'BALUNGAO',
      'BANI',
      'BASISTA',
      'BAUTISTA',
      'BAYAMBANG',
      'BINALONAN',
      'BINMALEY',
      'BOLINAO',
      'BUGALLON',
      'BURGOS',
      'CALASIAO',
      'CITY OF ALAMINOS',
      'CITY OF DAGUPAN',
      'CITY OF SAN CARLOS',
      'CITY OF URDANETA',
      'DASOL',
      'INFANTA',
      'LABRADOR',
      'LAOAC',
      'LINGAYEN (Capital)',
      'MABINI',
      'MALASIQUI',
      'MANAOAG',
      'MANGALDAN',
      'MANGATAREM',
      'MAPANDAN',
      'NATIVIDAD',
      'POZORRUBIO',
      'ROSALES',
      'SAN FABIAN',
      'SAN JACINTO',
      'SAN MANUEL',
      'SAN NICOLAS',
      'SAN QUINTIN',
      'SANTA BARBARA',
      'SANTA MARIA',
      'SANTO TOMAS',
      'SISON',
      'SUAL',
      'TAYUG',
      'UMINGAN',
      'URBIZTONDO',
      'VILLASIS',
      'AGDANGAN',
      'ALABAT',
      'ATIMONAN',
      'BUENAVISTA',
      'BURDEOS',
      'CALAUAG',
      'CANDELARIA',
      'CATANAUAN',
      'CITY OF LUCENA (Capital)',
      'CITY OF TAYABAS',
      'DOLORES',
      'GENERAL LUNA',
      'GENERAL NAKAR',
      'GUINAYANGAN',
      'GUMACA',
      'INFANTA',
      'JOMALIG',
      'LOPEZ',
      'LUCBAN',
      'MACALELON',
      'MAUBAN',
      'MULANAY',
      'PADRE BURGOS',
      'PAGBILAO',
      'PANUKULAN',
      'PATNANUNGAN',
      'PEREZ',
      'PITOGO',
      'PLARIDEL',
      'POLILLO',
      'QUEZON',
      'REAL',
      'SAMPALOC',
      'SAN ANDRES',
      'SAN ANTONIO',
      'SAN FRANCISCO (AURORA)',
      'SAN NARCISO',
      'SARIAYA',
      'TAGKAWAYAN',
      'TIAONG',
      'UNISAN',
      'AGLIPAY',
      'CABARROGUIS (Capital)',
      'DIFFUN',
      'MADDELA',
      'NAGTIPUNAN',
      'SAGUDAY',
      'ANGONO',
      'BARAS',
      'BINANGONAN',
      'CAINTA',
      'CARDONA',
      'CITY OF ANTIPOLO (Capital)',
      'JALA-JALA',
      'MORONG',
      'PILILLA',
      'RODRIGUEZ (MONTALBAN)',
      'SAN MATEO',
      'TANAY',
      'TAYTAY',
      'TERESA',
      'ALCANTARA',
      'BANTON',
      'CAJIDIOCAN',
      'CALATRAVA',
      'CONCEPCION',
      'CORCUERA',
      'FERROL',
      'LOOC',
      'MAGDIWANG',
      'ODIONGAN',
      'ROMBLON (Capital)',
      'SAN AGUSTIN',
      'SAN ANDRES',
      'SAN FERNANDO',
      'SAN JOSE',
      'SANTA FE',
      'SANTA MARIA (IMELDA)',
      'ALMAGRO',
      'BASEY',
      'CALBIGA',
      'CITY OF CALBAYOG',
      'CITY OF CATBALOGAN (Capital)',
      'DARAM',
      'GANDARA',
      'HINABANGAN',
      'JIABONG',
      'MARABUT',
      'MATUGUINAO',
      'MOTIONG',
      'PAGSANGHAN',
      'PARANAS (WRIGHT)',
      'PINABACDAO',
      'SAN JORGE',
      'SAN JOSE DE BUAN',
      'SAN SEBASTIAN',
      'SANTA MARGARITA',
      'SANTA RITA',
      'SANTO NIÑO',
      'TAGAPUL-AN',
      'TALALORA',
      'TARANGNAN',
      'VILLAREAL',
      'ZUMARRAGA',
      'ALABEL (Capital)',
      'CITY OF COTABATO',
      'GLAN',
      'KIAMBA',
      'MAASIM',
      'MAITUM',
      'MALAPATAN',
      'MALUNGON',
      'ENRIQUE VILLANUEVA',
      'LARENA',
      'LAZI',
      'MARIA',
      'SAN JUAN',
      'SIQUIJOR (Capital)',
      'BARCELONA',
      'BULAN',
      'BULUSAN',
      'CASIGURAN',
      'CASTILLA',
      'CITY OF SORSOGON (Capital)',
      'DONSOL',
      'GUBAT',
      'IROSIN',
      'JUBAN',
      'MAGALLANES',
      'MATNOG',
      'PILAR',
      'PRIETO DIAZ',
      'SANTA MAGDALENA',
      'BANGA',
      'CITY OF GENERAL SANTOS (DADIANGAS)',
      'CITY OF KORONADAL (Capital)',
      'LAKE SEBU',
      'NORALA',
      'POLOMOLOK',
      'SANTO NIÑO',
      'SURALLAH',
      'TBOLI',
      'TAMPAKAN',
      'TANTANGAN',
      'TUPI',
      'ANAHAWAN',
      'BONTOC',
      'CITY OF MAASIN (Capital)',
      'HINUNANGAN',
      'HINUNDAYAN',
      'LIBAGON',
      'LILOAN',
      'LIMASAWA',
      'MACROHON',
      'MALITBOG',
      'PADRE BURGOS',
      'PINTUYAN',
      'SAINT BERNARD',
      'SAN FRANCISCO',
      'SAN JUAN (CABALIAN)',
      'SAN RICARDO',
      'SILAGO',
      'SOGOD',
      'TOMAS OPPUS',
      'BAGUMBAYAN',
      'CITY OF TACURONG',
      'COLUMBIO',
      'ESPERANZA',
      'ISULAN (Capital)',
      'KALAMANSIG',
      'LAMBAYONG (MARIANO MARCOS)',
      'LEBAK',
      'LUTAYAN',
      'PALIMBANG',
      'PRESIDENT QUIRINO',
      'SEN. NINOY AQUINO',
      'HADJI PANGLIMA TAHIL (MARUNGGAS)',
      'INDANAN',
      'JOLO (Capital)',
      'KALINGALAN CALUANG',
      'LUGUS',
      'LUUK',
      'MAIMBUNG',
      'OLD PANAMAO',
      'OMAR',
      'PANDAMI',
      'PANGLIMA ESTINO (NEW PANAMAO)',
      'PANGUTARAN',
      'PARANG',
      'PATA',
      'PATIKUL',
      'SIASI',
      'TALIPAO',
      'TAPUL',
      'TONGKIL',
      'ALEGRIA',
      'BACUAG',
      'BURGOS',
      'CITY OF SURIGAO (Capital)',
      'CLAVER',
      'DAPA',
      'DEL CARMEN',
      'GENERAL LUNA',
      'GIGAQUIT',
      'MAINIT',
      'MALIMONO',
      'PILAR',
      'PLACER',
      'SAN BENITO',
      'SAN FRANCISCO (ANAO-AON)',
      'SAN ISIDRO',
      'SANTA MONICA (SAPAO)',
      'SISON',
      'SOCORRO',
      'TAGANA-AN',
      'TUBOD',
      'BAROBO',
      'BAYABAS',
      'CAGWAIT',
      'CANTILAN',
      'CARMEN',
      'CARRASCAL',
      'CITY OF BISLIG',
      'CITY OF TANDAG (Capital)',
      'CORTES',
      'HINATUAN',
      'LANUZA',
      'LIANGA',
      'LINGIG',
      'MADRID',
      'MARIHATAG',
      'SAN AGUSTIN',
      'SAN MIGUEL',
      'TAGBINA',
      'TAGO',
      'ANAO',
      'BAMBAN',
      'CAMILING',
      'CAPAS',
      'CITY OF TARLAC (Capital)',
      'CONCEPCION',
      'GERONA',
      'LA PAZ',
      'MAYANTOC',
      'MONCADA',
      'PANIQUI',
      'PURA',
      'RAMOS',
      'SAN CLEMENTE',
      'SAN JOSE',
      'SAN MANUEL',
      'SANTA IGNACIA',
      'VICTORIA',
      'BONGAO (Capital)',
      'LANGUYAN',
      'MAPUN (CAGAYAN DE TAWI-TAWI)',
      'PANGLIMA SUGALA (BALIMBING)',
      'SAPA-SAPA',
      'SIBUTU',
      'SIMUNUL',
      'SITANGKAI',
      'SOUTH UBIAN',
      'TANDUBAS',
      'TURTLE ISLANDS',
      'BOTOLAN',
      'CABANGAN',
      'CANDELARIA',
      'CASTILLEJOS',
      'CITY OF OLONGAPO',
      'IBA (Capital)',
      'MASINLOC',
      'PALAUIG',
      'SAN ANTONIO',
      'SAN FELIPE',
      'SAN MARCELINO',
      'SAN NARCISO',
      'SANTA CRUZ',
      'SUBIC',
      'BACUNGAN (Leon T. Postigo)',
      'BALIGUIAN',
      'CITY OF DAPITAN',
      'CITY OF DIPOLOG (Capital)',
      'GODOD',
      'GUTALAC',
      'JOSE DALMAN (PONOT)',
      'KALAWIT',
      'KATIPUNAN',
      'LA LIBERTAD',
      'LABASON',
      'LILOY',
      'MANUKAN',
      'MUTIA',
      'PIÑAN (NEW PIÑAN)',
      'POLANCO',
      'PRES. MANUEL A. ROXAS',
      'RIZAL',
      'SALUG',
      'SERGIO OSMEÑA SR.',
      'SIAYAN',
      'SIBUCO',
      'SIBUTAD',
      'SINDANGAN',
      'SIOCON',
      'SIRAWAI',
      'TAMPILISAN',
      'AURORA',
      'BAYOG',
      'CITY OF PAGADIAN (Capital)',
      'CITY OF ZAMBOANGA',
      'DIMATALING',
      'DINAS',
      'DUMALINAO',
      'DUMINGAG',
      'GUIPOS',
      'JOSEFINA',
      'KUMALARANG',
      'LABANGAN',
      'LAKEWOOD',
      'LAPUYAN',
      'MAHAYAG',
      'MARGOSATUBIG',
      'MIDSALIP',
      'MOLAVE',
      'PITOGO',
      'RAMON MAGSAYSAY (LIARGO)',
      'SAN MIGUEL',
      'SAN PABLO',
      'SOMINOT (DON MARIANO MARCOS)',
      'TABINA',
      'TAMBULIG',
      'TIGBAO',
      'TUKURAN',
      'VINCENZO A. SAGUN',
      'ALICIA',
      'BUUG',
      'CITY OF ISABELA',
      'DIPLAHAN',
      'IMELDA',
      'IPIL (Capital)',
      'KABASALAN',
      'MABUHAY',
      'MALANGAS',
      'NAGA',
      'OLUTANGA',
      'PAYAO',
      'ROSELLER LIM',
      'SIAY',
      'TALUSAN',
      'TITAY',
      'TUNGAWAN'
    ]
  })
}
